# Basic Site Information
title: "Kawaii Tarik's Bikepacking Blog"  # Update to your blog's name
author: Tarik Hasic  # Your name
email: tarik@example.com  # Your email
url: "https://trichardsonthefirst.github.io"  # Your domain
baseurl: ""  # Leave this blank since you're not using a subpath

# Description of your site
description: > 
  Follow my bikepacking adventures around the world, exploring new destinations and experiences!

# Favicon (make sure to upload the favicon file in the root folder)
favicon: "logo.png"

# Use permalink for cleaner URLs
permalink: /:slug.html

# Theme Configuration
theme: no-style-please  # Theme for GitHub Pages
theme_config:
  appearance: "auto"  # Can be "light", "dark", or "auto"
  back_home_text: "Back to Home"  # Customize the text that links back to the homepage
  date_format: "%Y-%m-%d"  # Customize how the date is displayed on posts
  show_description: true  # Show the description on the homepage

# Sass and Plugins
sass:
  style: :compressed

# Plugins for RSS feed and SEO tags
plugins:
  - jekyll-feed
  - jekyll-seo-tag
